name: client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.3
  location: ^4.3.0  # Add this line
  flutter_image_compress: ^1.1.0
  camera: ^0.9.4+18
  path_provider: ^2.0.9
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/jim.png
    - assets/images/01-cn-tower.jpg
    - assets/background.png